### PR TITLE
Change one missed unique FK field to OneToOne field

### PR DESCRIPTION
**Pull request by systemsoverload**
Missed one in the last PR

### CODE REVIEW

**Comment by kanet77** [comment]
I hate to even bring this up, but since you changed the migrations:

* Why are there migrations and south_migrations? Are these the only two reasonable migrations packages for Django and this is an attempt to support both?
* Should south_migrations also be updated? (e.g. this line for the [facebook](https://github.com/brodie/django-socialregistration/blob/master/socialregistration/contrib/facebook/south_migrations/0001_initial.py#L14) model)

**Comment by kanet77** [comment]
lgtm

**Comment by systemsoverload** [comment]
@kanet77 the south_migrations are just legacy AFAIK, they would only apply to django < 1.7 and I think we are still hopeful that this package will die (soon)

**Comment by mark-adams** [comment]
LGTM

**Pull request merged**
